---
_hotel_id: THE397
_portal_id: required-but-empty
_root_path: https://qa4.ttaws.com/rt
latitude: 42.34482
longitude: -71.09701
name: The Verb Hotel
email: steffan@traveltripper.io
phone_number: "--"
address:
  street1: 1271 Boylston St
  street2: ''
  state: Massachusetts
  city: Boston
  country: United States
  zip_code: '02215'
